name: 📋 Development Task
description: Create a development task for the Crypto Inventory Platform
title: "[TASK] "
labels: ["task", "needs-triage"]
projects: ["democorp/crypto-inventory-platform"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create development tasks, technical debt items, or implementation work.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this task relate to?
      options:
        - Authentication Service
        - Inventory Service
        - Compliance Engine
        - Report Generator
        - Sensor Manager
        - Integration Service
        - AI Analysis Service
        - Network Sensor
        - Web Frontend
        - Database
        - Infrastructure
        - Documentation
        - DevOps/CI-CD
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What type of development task is this?
      options:
        - Implementation (New feature development)
        - Refactoring (Code improvement)
        - Technical Debt (Address existing issues)
        - Testing (Add/improve tests)
        - Documentation (Update docs)
        - Performance (Optimization work)
        - Security (Security improvements)
        - Infrastructure (DevOps/deployment)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What's the priority of this task?
      options:
        - Critical (Must be done immediately)
        - High (Important for current milestone)
        - Medium (Should be done soon)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Detailed description of what needs to be done
      placeholder: Describe the task in detail...
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Specific requirements and constraints
      placeholder: |
        - Requirement 1
        - Requirement 2
        - Requirement 3

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes
      description: Any technical details, approaches, or considerations
      placeholder: Technical implementation details, API changes, etc...

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other tasks or components does this depend on?
      placeholder: |
        - Depends on #123
        - Requires completion of authentication service
        - Needs database schema changes

  - type: input
    id: estimate
    attributes:
      label: Time Estimate
      description: Estimated effort (e.g., "2 days", "1 week", "3 story points")
      placeholder: e.g., "3 days"

  - type: checkboxes
    id: considerations
    attributes:
      label: Additional Considerations
      options:
        - label: Requires API documentation updates
        - label: Requires database migrations
        - label: Requires UI/UX design
        - label: Affects security model
        - label: Requires performance testing
        - label: Needs integration testing
        - label: Requires deployment changes
